version: "3.8"
services:
  d_mysql_db:
    image: mysql/mysql-server:latest
    container_name: d_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: __password__
    ports:
      - 3307:3306
    volumes:
      - ${CONF_DIR}:/etc/mysql/conf.d
      - ${DATA_DIR}:/var/lib/mysql
